name: news_app_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ionicons: ^0.1.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.0
  intl: ^0.18.1
  retrofit: ^3.0.1
  dio: ^4.0.6
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.5
  firebase_auth: ^4.10.0
  flutter_hooks: ^0.18.3
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: ^3.0.1+1
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
